name: build-app

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:
    inputs:
      build-configs:
        type: choice
        description: build-configs
        options:
          - '[\"app-store\"]'
          - '[\"developer-id\"]'
          - '[\"ios\"]'
        required: false

jobs:
  jobs-filter:
    name: Filter Jobs
    uses: ./.github/workflows/jobs-filter.yml

  build-app:
    name: Build App
    needs: [jobs-filter]
    if: needs.jobs-filter.outputs.should-build-app == 'true'
    uses: grigorye/ReusableWorkflows/.github/workflows/build-app-generic.yml@v22
    with:
      macos-app-scheme: macOS-app
      ios-app-scheme: iOS-app
      build-configs: ${{ github.event.inputs.build-configs }}
      runs-on: macos-12
    secrets: inherit

  finalize-build-app:
    name: Finalize App Build
    if: always()
    needs: [jobs-filter, build-app]
    runs-on: ubuntu-latest
    steps:
      - name: Check sanity for should-build-app
        if: ${{ !(needs.jobs-filter.outputs.should-build-app == 'true') && !(needs.jobs-filter.outputs.should-build-app == 'false') }}
        run:
          exit 1
      - name: Check sanity for should-finalize-build-app
        if: ${{ !(needs.jobs-filter.outputs.should-finalize-build-app == 'true') && !(needs.jobs-filter.outputs.should-finalize-build-app == 'true') }}
        run:
          exit 1
      - name: Check required build results
        if: needs.jobs-filter.outputs.should-build-app == 'true'
        run: |
          [ "${{ needs.build-app.result }}" == "success" ]
      - name: Report success for skipped build
        if: needs.jobs-filter.outputs.should-build-app == 'false'
        run: |
          [ "${{ needs.jobs-filter.outputs.should-finalize-build-app }}" == "true" ]
