name: build-app

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: [master]
  workflow_dispatch:
    inputs:
      build-configs:
        type: choice
        description: build-configs
        options:
          - '[\"app-store\"]'
          - '[\"developer-id\"]'
          - '[\"ios\"]'
        required: false

jobs:
  build:
    name: 'App'
    if: contains(github.event.pull_request.labels.*.name, 'ready to go') || github.event_name != 'pull_request'
    uses: grigorye/ReusableWorkflows/.github/workflows/build-app-generic.yml@v3
    with:
      macos-app-scheme: 'macOS-app'
      ios-app-scheme: 'iOS-app'
      build-configs: ${{ github.event.inputs.build-configs }}
    secrets: inherit
