name: build-app

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  workflow_dispatch:
    inputs:
      build-configs:
        type: choice
        description: build-configs
        options:
          - '[\"app-store\"]'
          - '[\"developer-id\"]'
          - '[\"ios\"]'
        required: false

jobs:
  jobs-filter:
    uses: ./.github/workflows/jobs-filter.yml

  build-app:
    name: App
    needs: [jobs-filter]
    if: needs.jobs-filter.outputs.should-build-app == 'true'
    uses: grigorye/ReusableWorkflows/.github/workflows/build-app-generic.yml@v5
    with:
      macos-app-scheme: macOS-app
      ios-app-scheme: iOS-app
      build-configs: ${{ github.event.inputs.build-configs }}
    secrets: inherit
