name: build-app

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
  workflow_dispatch:
    inputs:
      build-configs:
        type: choice
        description: build-configs
        options:
          - "['app-store']"
          - "['developer-id']"
          - "['ios']"
        required: true

jobs:
  build:
    name: 'App'
    uses: grigorye/ReusableWorkflows/.github/workflows/build-app-generic.yml@4391946b0d291b749328083f7ee3cc3f6355a89b
    with:
      macos-app-scheme: 'macOS-app'
      ios-app-scheme: 'iOS-app'
      build-configs: ${{ github.event.inputs.build-configs }}
    secrets: inherit
