name: jobs-filter

on:
  workflow_call:
    outputs:
      should-build-app:
        description: 'Whether to build-app or not.'
        value: ${{ github.event.pull_request.draft != true && jobs.paths-filter.outputs.should-build != 'false' }}
      should-finalize-build-app:
        description: 'Whether to finalize-build-app or not.'
        value: ${{ github.event.pull_request.draft != true }}

jobs:
  paths-filter:
    name: 'Check Paths'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      should-build: ${{ steps.build-check.outputs.should-build }}
    steps:
      - id: build-check
        if: github.event_name == 'pull_request'
        uses: dorny/paths-filter@v2
        with:
          filters: |
            should-build:
              - '.github/**'
              - 'Brewfile.*'
              - 'Brewfile'
              - 'Commands/**'
              - 'dist/**'
              - 'GHAScripts/**'
              - 'GHAShortcuts/**'
              - 'Mintfile'
              - 'Modules/**'
              - 'project.yml'
              - 'ReusableWorkflows/**'
              - 'Targets/**'
              - 'ThirdParties/**'
              - 'Xcodegen/**'
              - 'Xcodeproj/**'
              - 'Sources/**'
              - 'Tuist'
              - '*.xcodeproj'
              - '*.xcworkspace'
              - '*.swift'
              - 'Derived'
